/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.medidata.avroserver.protocol.v1;

@SuppressWarnings("all")
public interface AvroTwoWayResponse {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"AvroTwoWayResponse\",\"namespace\":\"com.medidata.avroserver.protocol.v1\",\"types\":[{\"type\":\"record\",\"name\":\"TwoWay\",\"fields\":[{\"name\":\"adSpace\",\"type\":\"string\"},{\"name\":\"adName\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"AvroResponse\",\"fields\":[{\"name\":\"ads\",\"type\":{\"type\":\"array\",\"items\":\"TwoWay\"}},{\"name\":\"errors\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"default\":[]}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends AvroTwoWayResponse {
    public static final org.apache.avro.Protocol PROTOCOL = com.medidata.avroserver.protocol.v1.AvroTwoWayResponse.PROTOCOL;
  }
}